# Generated by Django 5.0 on 2026-01-26 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blockchain_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('GREEN', 'Safe'), ('YELLOW', 'Warning'), ('RED', 'Emergency')], default='GREEN', max_length=10)),
                ('last_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_movement_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_in_danger_zone', models.BooleanField(default=False)),
            ],
        ),
    ]
