# Generated by Django 5.0.4 on 2026-05-26 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourists", "0002_traveler"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveler",
            name="last_lat",
        ),
        migrations.RemoveField(
            model_name="traveler",
            name="last_lon",
        ),
        migrations.AddField(
            model_name="traveler",
            name="current_region",
            field=models.CharField(
                default="Nagaland",
                help_text="Used to filter which police department sees this traveler",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="emergency_contact",
            field=models.CharField(
                blank=True, help_text="Name and Phone Number", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="last_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="last_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="traveler",
            name="location_name",
            field=models.CharField(
                blank=True, help_text="e.g., Dzüko Valley Forest", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="medical_info",
            field=models.TextField(
                blank=True, help_text="Medical history, blood type, allergies"
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="status_note",
            field=models.CharField(
                blank=True, help_text="e.g., SOS Button Triggered", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="traveler",
            name="traveler_id",
            field=models.CharField(default="TEMP_ID", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="traveler",
            name="blockchain_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="traveler",
            name="status",
            field=models.CharField(
                choices=[
                    ("safe", "Safe"),
                    ("warning", "Warning"),
                    ("emergency", "Emergency / Unresponsive"),
                ],
                default="safe",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuthorityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        help_text="e.g., Kohima Central Police", max_length=150
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(help_text="e.g., Nagaland, Assam", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
